# Generated by Django 4.2.3 on 2023-09-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0004_produtos_marca"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/gerencia/images"
            ),
        ),
    ]
