# Generated by Django 4.2.3 on 2023-09-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0005_produtos_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
