# Generated by Django 4.2.3 on 2023-09-18 00:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0006_alter_produtos_id"),
        ("gerencia", "0006_alter_produtos_imagem"),
    ]

    operations = []
