# Generated by Django 4.2.3 on 2023-11-18 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0008_alter_produtos_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="data_entrada",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="produtos",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="gerencia/static/gerencia/images"
            ),
        ),
    ]
