# Generated by Django 4.2.3 on 2023-11-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0009_produtos_data_entrada_alter_produtos_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="data_saida",
            field=models.DateTimeField(null=True),
        ),
    ]
