# Generated by Django 4.2.3 on 2023-11-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0010_produtos_data_saida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="data_saida",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
