# Generated by Django 4.2.3 on 2023-11-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0012_logestoque"),
    ]

    operations = [
        migrations.AddField(
            model_name="logestoque",
            name="nome",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
