# Generated by Django 4.2.3 on 2023-12-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0013_logestoque_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logestoque",
            name="nome",
        ),
        migrations.CreateModel(
            name="ResumoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                ("data", models.DateTimeField()),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gerencia.produtos",
                    ),
                ),
            ],
        ),
    ]
