# Generated by Django 4.2.3 on 2023-12-01 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0014_remove_logestoque_nome_resumoestoque"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResumoEstoque",
        ),
    ]
