# Generated by Django 4.2.3 on 2023-12-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0015_delete_resumoestoque"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=65)),
                ("quantidade", models.IntegerField()),
                ("data", models.DateTimeField()),
                ("tipo", models.CharField(max_length=10)),
            ],
        ),
    ]
