# Generated by Django 4.2.3 on 2023-12-01 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0016_resumoestoque"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resumoestoque",
            name="tipo",
        ),
    ]
