# Generated by Django 4.2.3 on 2023-12-01 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0017_remove_resumoestoque_tipo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resumoestoque",
            options={"managed": False},
        ),
    ]
