# Generated by Django 4.2.3 on 2023-12-01 03:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0018_alter_resumoestoque_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResumoEstoque",
        ),
        migrations.AlterModelOptions(
            name="logestoque",
            options={"managed": False},
        ),
    ]
