# Generated by Django 4.2.3 on 2023-12-01 03:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0019_delete_resumoestoque_alter_logestoque_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logestoque",
            options={},
        ),
    ]
