# Generated by Django 4.2.3 on 2023-12-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0021_estoqueproduto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logestoque",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
