# Generated by Django 4.2.3 on 2023-12-01 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0022_alter_logestoque_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaldoEstoque",
            fields=[
                (
                    "produto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="gerencia.produtos",
                    ),
                ),
                ("saldo", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="EstoqueProduto",
        ),
    ]
