# Generated by Django 4.2.3 on 2023-12-01 23:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0023_saldoestoque_delete_estoqueproduto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SaldoEstoque",
        ),
    ]
