# Generated by Django 4.2.3 on 2023-12-01 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0024_delete_saldoestoque"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaldoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidadet", models.IntegerField(default=0)),
                ("data_mov", models.DateTimeField(auto_now_add=True)),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gerencia.logestoque",
                    ),
                ),
            ],
        ),
    ]
