# Generated by Django 4.2.3 on 2023-12-01 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gerencia", "0025_saldoestoque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saldoestoque",
            name="log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gerencia.produtos"
            ),
        ),
    ]
